// esto sirve para juntar la ficha tecnica real de los productos extra que no estaban en la semilla original

import {
    plantillaEspecificacionesDisco,
    plantillaEspecificacionesSsd,
    plantillaEspecificacionesMemoria,
    plantillaEspecificacionesProcesador,
    plantillaEspecificacionesVideo,
    plantillaEspecificacionesPlacaMadre,
    plantillaEspecificacionesFuentePoder,
    plantillaEspecificacionesEnfriamiento
} from './plantillas_especificaciones_tecnicas'

export const productos_extra = [
    { nombre: '990 Pro 2TB', especificaciones_tecnicas: plantillaEspecificacionesSsd({ capacidad: '2 TB', factor_forma: 'M.2 2280', temperatura: '0°C a 70°C', interfaz: 'PCIe 4.0 x4 NVMe', ancho: '22 mm', peso: '9 g', profundidad: '80 mm', altura: '2.3 mm', componente_para: 'Gaming y creacion de contenido', compatible_nvme: 'Si', velocidad_lectura: '7450 MB/s', velocidad_escritura: '6900 MB/s' }) },
    { nombre: 'Barracuda 2TB', especificaciones_tecnicas: plantillaEspecificacionesDisco({ capacidad: '2 TB', factor_forma: '3.5 pulgadas', temperatura: '5°C a 60°C', interfaz: 'SATA III 6 Gb/s', ancho: '101.6 mm', peso: '450 g', profundidad: '147 mm', altura: '20.2 mm', componente_para: 'PC de escritorio', compatible_nvme: 'No', tipo_disco: '7200 RPM', velocidad_escritura: '190 MB/s' }) },
    { nombre: 'Black SN770 1TB', especificaciones_tecnicas: plantillaEspecificacionesSsd({ capacidad: '1 TB', factor_forma: 'M.2 2280', temperatura: '0°C a 70°C', interfaz: 'PCIe 4.0 x4 NVMe', ancho: '22 mm', peso: '7 g', profundidad: '80 mm', altura: '2.38 mm', componente_para: 'Gaming y consolas', compatible_nvme: 'Si', velocidad_lectura: '5150 MB/s', velocidad_escritura: '4900 MB/s' }) },
    { nombre: 'P3 Plus 1TB', especificaciones_tecnicas: plantillaEspecificacionesSsd({ capacidad: '1 TB', factor_forma: 'M.2 2280', temperatura: '0°C a 70°C', interfaz: 'PCIe 4.0 x4 NVMe', ancho: '22 mm', peso: '7 g', profundidad: '80 mm', altura: '2.3 mm', componente_para: 'Almacenamiento economico y gaming', compatible_nvme: 'Si', velocidad_lectura: '5000 MB/s', velocidad_escritura: '3600 MB/s' }) },

    { nombre: 'AK620', especificaciones_tecnicas: plantillaEspecificacionesEnfriamiento({ tipo: 'Disipador de aire de doble torre', socket: 'Intel LGA1700/1200 y AMD AM4/AM5', material: 'Base de cobre con heat pipes de niquel', heat_pipes: '6 heat pipes', ancho: '128 mm', peso: '1200 g', profundidad: '137 mm', altura: '160 mm', componente_para: 'Enfriamiento de CPU de alto TDP', tdp_soportado: 'Hasta 260 W', ruido: '≤28 dBA', velocidad_ventilador: '500-1850 RPM' }) },
    { nombre: 'NH-D15', especificaciones_tecnicas: plantillaEspecificacionesEnfriamiento({ tipo: 'Disipador de aire de doble torre', socket: 'Intel LGA1700/1200 y AMD AM4/AM5', material: 'Base niquelada con heat pipes de cobre', heat_pipes: '6 heat pipes', ancho: '150 mm', peso: '1320 g', profundidad: '161 mm', altura: '165 mm', componente_para: 'Enfriamiento silencioso de alto rendimiento', tdp_soportado: 'Hasta 250 W', ruido: '≤24.6 dBA', velocidad_ventilador: '300-1500 RPM' }) },

    { nombre: 'Fuente de Poder Corsair CX650', especificaciones_tecnicas: plantillaEspecificacionesFuentePoder({ potencia: '650 W', certificacion: '80 Plus Bronze', modularidad: 'Semi-modular', factor_forma: 'ATX', ancho: '150 mm', peso: '1800 g', profundidad: '140 mm', altura: '86 mm', componente_para: 'PC gaming de gama media', eficiencia: '85% de eficiencia tipica', conectores_pcie: '2 conectores PCIe 6+2 pin', ventilador: '120 mm silencioso' }) },
    { nombre: 'RM750e 750W', especificaciones_tecnicas: plantillaEspecificacionesFuentePoder({ potencia: '750 W', certificacion: '80 Plus Gold', modularidad: 'Full modular', factor_forma: 'ATX', ancho: '150 mm', peso: '2000 g', profundidad: '160 mm', altura: '86 mm', componente_para: 'PC gaming de alto rendimiento', eficiencia: '90% de eficiencia tipica', conectores_pcie: '4 conectores PCIe 6+2 pin', ventilador: '105 mm ZeroRPM' }) },
    { nombre: 'SuperNOVA 850 G6', especificaciones_tecnicas: plantillaEspecificacionesFuentePoder({ potencia: '850 W', certificacion: '80 Plus Gold', modularidad: 'Full modular', factor_forma: 'ATX', ancho: '150 mm', peso: '2100 g', profundidad: '150 mm', altura: '86 mm', componente_para: 'PC gaming de gama alta y workstation', eficiencia: 'Mas de 90% de eficiencia', conectores_pcie: '6 conectores PCIe 6+2 pin', ventilador: '135 mm con modo silencioso' }) },

    { nombre: 'Fury Beast 32GB DDR5', especificaciones_tecnicas: plantillaEspecificacionesMemoria({ capacidad: '32 GB (2x16GB)', factor_forma: 'DIMM', frecuencia: 'DDR5-5600 MHz', latencia: 'CL36', ancho: '133 mm', peso: '32 g por modulo', profundidad: '7 mm', altura: '34.9 mm', componente_para: 'Gaming y multitarea', voltaje: '1.25 V', tecnologia: 'Intel XMP 3.0', velocidad_transferencia: '44.8 GB/s' }) },
    { nombre: 'Trident Z5 32GB DDR5', especificaciones_tecnicas: plantillaEspecificacionesMemoria({ capacidad: '32 GB (2x16GB)', factor_forma: 'DIMM', frecuencia: 'DDR5-6000 MHz', latencia: 'CL30', ancho: '133 mm', peso: '38 g por modulo', profundidad: '7 mm', altura: '44 mm', componente_para: 'Gaming y overclock', voltaje: '1.35 V', tecnologia: 'Intel XMP 3.0', velocidad_transferencia: '48 GB/s' }) },
    { nombre: 'Vengeance LPX 32GB DDR4', especificaciones_tecnicas: plantillaEspecificacionesMemoria({ capacidad: '32 GB (2x16GB)', factor_forma: 'DIMM', frecuencia: 'DDR4-3200 MHz', latencia: 'CL16', ancho: '133 mm', peso: '30 g por modulo', profundidad: '7 mm', altura: '34.9 mm', componente_para: 'Builds AM4/Intel de gama media', voltaje: '1.35 V', tecnologia: 'Intel XMP 2.0', velocidad_transferencia: '25.6 GB/s' }) },

    { nombre: 'Core i3 12100F', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '4 nucleos 8 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '20 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'PC de oficina y gaming basico', frecuencia_base: '3.3 GHz', frecuencia_turbo: '4.3 GHz', tdp: '58 W' }) },
    { nombre: 'Core i5 12400F', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '6 nucleos 12 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '22 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming 1080p de entrada', frecuencia_base: '2.5 GHz', frecuencia_turbo: '4.4 GHz', tdp: '65 W' }) },
    { nombre: 'Core i5 13400F', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '10 nucleos (6P+4E) 16 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '24 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming 1080p/1440p equilibrado', frecuencia_base: '2.5 GHz', frecuencia_turbo: '4.6 GHz', tdp: '65 W' }) },
    { nombre: 'Core i5 14600K', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '14 nucleos (6P+8E) 20 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '33 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming 1080p/1440p alto rendimiento', frecuencia_base: '3.5 GHz', frecuencia_turbo: '5.3 GHz', tdp: '125 W' }) },
    { nombre: 'Core i7 12700K', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '12 nucleos (8P+4E) 20 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '32 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming y produccion de contenido', frecuencia_base: '3.6 GHz', frecuencia_turbo: '5.0 GHz', tdp: '125 W' }) },
    { nombre: 'Core i7 13700K', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '16 nucleos (8P+8E) 24 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '33 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming y creacion de contenido', frecuencia_base: '3.4 GHz', frecuencia_turbo: '5.4 GHz', tdp: '125 W' }) },
    { nombre: 'Core i7 14700K', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '20 nucleos (8P+12E) 28 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '34 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming y contenido profesional', frecuencia_base: '3.4 GHz', frecuencia_turbo: '5.6 GHz', tdp: '125 W' }) },
    { nombre: 'Core i9 14900K', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '24 nucleos (8P+16E) 32 hilos', factor_forma: 'BGA/LGA', temperatura: '0°C a 100°C', socket: 'LGA1700', ancho: '37.5 mm', peso: '35 g', profundidad: '37.5 mm', altura: '3.9 mm', componente_para: 'Gaming extremo y workstation', frecuencia_base: '3.2 GHz', frecuencia_turbo: '6.0 GHz', tdp: '125 W (253 W turbo)' }) },
    { nombre: 'Ryzen 5 5600', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '6 nucleos 12 hilos', factor_forma: 'PGA', temperatura: '0°C a 90°C', socket: 'AM4', ancho: '40 mm', peso: '27 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming 1080p economico', frecuencia_base: '3.5 GHz', frecuencia_turbo: '4.4 GHz', tdp: '65 W' }) },
    { nombre: 'Ryzen 5 7600', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '6 nucleos 12 hilos', factor_forma: 'PGA', temperatura: '0°C a 95°C', socket: 'AM5', ancho: '40 mm', peso: '28 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming 1080p/1440p moderno', frecuencia_base: '3.8 GHz', frecuencia_turbo: '5.1 GHz', tdp: '65 W' }) },
    { nombre: 'Ryzen 7 5700X', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '8 nucleos 16 hilos', factor_forma: 'PGA', temperatura: '0°C a 90°C', socket: 'AM4', ancho: '40 mm', peso: '29 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming y multitarea AM4', frecuencia_base: '3.4 GHz', frecuencia_turbo: '4.6 GHz', tdp: '65 W' }) },
    { nombre: 'Ryzen 7 7700', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '8 nucleos 16 hilos', factor_forma: 'PGA', temperatura: '0°C a 95°C', socket: 'AM5', ancho: '40 mm', peso: '30 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming y productividad eficiente', frecuencia_base: '3.8 GHz', frecuencia_turbo: '5.3 GHz', tdp: '65 W' }) },
    { nombre: 'Ryzen 7 7800X3D', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '8 nucleos 16 hilos', factor_forma: 'PGA', temperatura: '0°C a 89°C', socket: 'AM5', ancho: '40 mm', peso: '31 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming competitivo con 3D V-Cache', frecuencia_base: '4.2 GHz', frecuencia_turbo: '5.0 GHz', tdp: '120 W' }) },
    { nombre: 'Ryzen 9 7900X', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '12 nucleos 24 hilos', factor_forma: 'PGA', temperatura: '0°C a 95°C', socket: 'AM5', ancho: '40 mm', peso: '32 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Gaming y creacion de contenido', frecuencia_base: '4.7 GHz', frecuencia_turbo: '5.6 GHz', tdp: '170 W' }) },
    { nombre: 'Ryzen 9 7950X', especificaciones_tecnicas: plantillaEspecificacionesProcesador({ nucleos: '16 nucleos 32 hilos', factor_forma: 'PGA', temperatura: '0°C a 95°C', socket: 'AM5', ancho: '40 mm', peso: '33 g', profundidad: '40 mm', altura: '3.5 mm', componente_para: 'Workstation y gaming extremo', frecuencia_base: '4.5 GHz', frecuencia_turbo: '5.7 GHz', tdp: '170 W' }) },

    { nombre: 'GeForce RTX 4060 Dual', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '8 GB GDDR6', factor_forma: 'ATX de doble slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x8', ancho: '229 mm', peso: '650 g', profundidad: '127 mm', altura: '40 mm', componente_para: 'Gaming 1080p eficiente', tgp: '115 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2460 MHz boost' }) },
    { nombre: 'GeForce RTX 4060 Ti Ventus', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '8 GB GDDR6', factor_forma: 'ATX de doble slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x8', ancho: '242 mm', peso: '750 g', profundidad: '112 mm', altura: '42 mm', componente_para: 'Gaming 1080p/1440p', tgp: '160 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2535 MHz boost' }) },
    { nombre: 'GeForce RTX 4070 Super Windforce', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '12 GB GDDR6X', factor_forma: 'ATX de doble slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x16', ancho: '267 mm', peso: '1000 g', profundidad: '130 mm', altura: '50 mm', componente_para: 'Gaming 1440p alto', tgp: '220 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2505 MHz boost' }) },
    { nombre: 'GeForce RTX 4070 Ti Super TUF', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '16 GB GDDR6X', factor_forma: 'ATX de triple slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x16', ancho: '318 mm', peso: '1500 g', profundidad: '135 mm', altura: '55 mm', componente_para: 'Gaming 1440p/4K de entrada', tgp: '285 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2610 MHz boost' }) },
    { nombre: 'GeForce RTX 4080 Super Gaming X', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '16 GB GDDR6X', factor_forma: 'ATX de triple slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x16', ancho: '336 mm', peso: '1600 g', profundidad: '140 mm', altura: '58 mm', componente_para: 'Gaming 4K de alto rendimiento', tgp: '320 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2610 MHz boost' }) },
    { nombre: 'GeForce RTX 4090 Gaming OC', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '24 GB GDDR6X', factor_forma: 'ATX de triple slot', temperatura: '0°C a 90°C', interfaz: 'PCIe 4.0 x16', ancho: '340 mm', peso: '2100 g', profundidad: '150 mm', altura: '58 mm', componente_para: 'Gaming 4K y render profesional', tgp: '450 W', ray_tracing: 'DLSS 3 con Frame Generation', velocidad_reloj: '2565 MHz boost' }) },
    { nombre: 'Radeon RX 7600 Dual', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '8 GB GDDR6', factor_forma: 'ATX de doble slot', temperatura: '0°C a 110°C', interfaz: 'PCIe 4.0 x8', ancho: '242 mm', peso: '700 g', profundidad: '112 mm', altura: '40 mm', componente_para: 'Gaming 1080p economico', tgp: '165 W', ray_tracing: 'Ray Tracing RDNA3 basico', velocidad_reloj: '2655 MHz boost' }) },
    { nombre: 'Radeon RX 7700 XT Gaming OC', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '12 GB GDDR6', factor_forma: 'ATX de triple slot', temperatura: '0°C a 110°C', interfaz: 'PCIe 4.0 x16', ancho: '298 mm', peso: '1100 g', profundidad: '130 mm', altura: '50 mm', componente_para: 'Gaming 1440p', tgp: '245 W', ray_tracing: 'Ray Tracing RDNA3', velocidad_reloj: '2599 MHz boost' }) },
    { nombre: 'Radeon RX 7800 XT Dual', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '16 GB GDDR6', factor_forma: 'ATX de doble/triple slot', temperatura: '0°C a 110°C', interfaz: 'PCIe 4.0 x16', ancho: '267 mm', peso: '1050 g', profundidad: '128 mm', altura: '50 mm', componente_para: 'Gaming 1440p alto', tgp: '263 W', ray_tracing: 'Ray Tracing RDNA3', velocidad_reloj: '2430 MHz boost' }) },
    { nombre: 'Radeon RX 7900 GRE Fighter', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '16 GB GDDR6', factor_forma: 'ATX de triple slot', temperatura: '0°C a 110°C', interfaz: 'PCIe 4.0 x16', ancho: '287 mm', peso: '1200 g', profundidad: '132 mm', altura: '52 mm', componente_para: 'Gaming 1440p/4K equilibrado', tgp: '260 W', ray_tracing: 'Ray Tracing RDNA3', velocidad_reloj: '2245 MHz boost' }) },
    { nombre: 'Radeon RX 7900 XTX Nitro+', especificaciones_tecnicas: plantillaEspecificacionesVideo({ memoria_video: '24 GB GDDR6', factor_forma: 'ATX de triple slot', temperatura: '0°C a 110°C', interfaz: 'PCIe 4.0 x16', ancho: '320 mm', peso: '1500 g', profundidad: '135 mm', altura: '55 mm', componente_para: 'Gaming 4K de alto rendimiento', tgp: '355 W', ray_tracing: 'Ray Tracing mejorado RDNA3', velocidad_reloj: '2565 MHz boost' }) },

    { nombre: 'B650 Aorus Elite AX', especificaciones_tecnicas: plantillaEspecificacionesPlacaMadre({ socket: 'AM5', chipset: 'AMD B650', factor_forma: 'ATX', memoria_compatible: 'DDR5 hasta 128GB', ancho: '305 mm', peso: '1100 g', profundidad: '244 mm', altura: '30 mm', componente_para: 'Builds Ryzen 7000/9000 de gama media-alta', ranuras_pcie: 'PCIe 4.0 x16 + PCIe 4.0 x4', puertos_sata: '4 puertos SATA III', soporte_m2: '2 ranuras M.2 PCIe 4.0' }) },
    { nombre: 'MAG B550 Tomahawk', especificaciones_tecnicas: plantillaEspecificacionesPlacaMadre({ socket: 'AM4', chipset: 'AMD B550', factor_forma: 'ATX', memoria_compatible: 'DDR4 hasta 128GB', ancho: '305 mm', peso: '1050 g', profundidad: '244 mm', altura: '30 mm', componente_para: 'Builds Ryzen 5000 de gama media', ranuras_pcie: 'PCIe 4.0 x16 + PCIe 3.0 x4', puertos_sata: '6 puertos SATA III', soporte_m2: '2 ranuras M.2 (una PCIe 4.0)' }) },
    { nombre: 'PRO Z790 A Max', especificaciones_tecnicas: plantillaEspecificacionesPlacaMadre({ socket: 'LGA1700', chipset: 'Intel Z790', factor_forma: 'ATX', memoria_compatible: 'DDR5 hasta 192GB', ancho: '305 mm', peso: '1150 g', profundidad: '244 mm', altura: '30 mm', componente_para: 'Builds Intel 12/13/14 gen de gama alta', ranuras_pcie: 'PCIe 5.0 x16 + PCIe 3.0 x4', puertos_sata: '6 puertos SATA III', soporte_m2: '4 ranuras M.2 PCIe 4.0' }) },
    { nombre: 'ROG Strix Z790 F Gaming', especificaciones_tecnicas: plantillaEspecificacionesPlacaMadre({ socket: 'LGA1700', chipset: 'Intel Z790', factor_forma: 'ATX', memoria_compatible: 'DDR5 hasta 128GB', ancho: '305 mm', peso: '1300 g', profundidad: '244 mm', altura: '30 mm', componente_para: 'Builds Intel gaming de alta gama', ranuras_pcie: 'PCIe 5.0 x16 + PCIe 4.0 x4', puertos_sata: '6 puertos SATA III', soporte_m2: '4 ranuras M.2 (una con disipador)' }) },
    { nombre: 'TUF Gaming B650 Plus', especificaciones_tecnicas: plantillaEspecificacionesPlacaMadre({ socket: 'AM5', chipset: 'AMD B650', factor_forma: 'ATX', memoria_compatible: 'DDR5 hasta 128GB', ancho: '305 mm', peso: '1080 g', profundidad: '244 mm', altura: '30 mm', componente_para: 'Builds Ryzen 7000/9000 de gama media', ranuras_pcie: 'PCIe 4.0 x16 + PCIe 3.0 x1', puertos_sata: '4 puertos SATA III', soporte_m2: '2 ranuras M.2 PCIe 4.0' }) }
]
